### ISSUE TITLE
Caught TypeError while rendering: character mapping must return integer, None, or unicode

### ISSUE THREAD

**Issue by yourcelf** [dziegler/django-urlcrypt#3]
At least in python 2.6 under linux, the key passed to `hmac.new(key, msg, digestmod)` must be of type str, not unicode.  However, as the key is constructed using User's passwords, if that field is unicode (as it is in recent Djangos), the key is cast to unicode.  This results in the following very confusing error:

```
TemplateSyntaxError at ...
Caught TypeError while rendering: character mapping must return integer, None or unicode
```

This can be fixed by simply coercing the key to string; though if the key had un-decodable unicode chars it would be another problem.

Patch:

```
--- a/urlcrypt/lib.py
+++ b/urlcrypt/lib.py
@@ -52,7 +52,7 @@ deobfuscate = obfuscate

 def encode_token(strings, secret_key_f):
     secret_key = secret_key_f(*strings)
-    signature = hmac.new(secret_key, pack(*strings), sha_hmac).hexdigest()
+    signature = hmac.new(str(secret_key), pack(*strings), sha_hmac).hexdigest()
     packed_string = pack(signature, *strings)
     return obfuscate(packed_string)
```

**Comment by lupulin** [comment]
I could be wrong, but I'm trying to figure this out for my own Django website for which I implemented something sort of similar. If you coerce the second parameter of hmac.new as an ASCII string instead of Unicode, you don't get "UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position ... " errors if there happens to be a Unicode character in the data...
